# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusdrive',
            old_name='dateofplacement',
            new_name='dateofdrive',
        ),
        migrations.AddField(
            model_name='placements',
            name='dateofplacement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
