# Generated by Django 2.0.6 on 2018-07-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='celery_schedule',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='celery_schedule',
            field=models.IntegerField(default=0),
        ),
    ]
