# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_auto_20170804_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placements',
            old_name='dateofplacement',
            new_name='dateofjoining',
        ),
        migrations.RemoveField(
            model_name='campusdrive',
            name='dateofjoining',
        ),
    ]
